SET VOICES 64
SET STREAMS 90
ADD CHANNEL
SET CHANNEL AUDIO_OUTPUT_TYPE 0 JACK
SET CHANNEL MIDI_INPUT_TYPE 0 JACK
SET CHANNEL MIDI_INPUT_PORT 0 0
SET CHANNEL MIDI_INPUT_CHANNEL 0 0
LOAD ENGINE SF2 0
LOAD INSTRUMENT NON_MODAL '/workdir/FluidR3\x5fGM\x2esf2' 97 0
ADD MIDI_INSTRUMENT_MAP 'Chromatic'
SET CHANNEL MIDI_INSTRUMENT_MAP 0 0
